# Generated by Django 4.0.2 on 2022-04-29 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_file_tutorialfiles_tutorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questionier',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='attached_files',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='tutorialfiles',
            name='document',
        ),
        migrations.RemoveField(
            model_name='tutorialfiles',
            name='images',
        ),
        migrations.RemoveField(
            model_name='tutorialfiles',
            name='videos',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
        migrations.DeleteModel(
            name='TutorialFiles',
        ),
    ]
