# Generated by Django 4.0.2 on 2022-05-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_rename_body_article_content_article_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_img',
            field=models.ImageField(null=True, upload_to='cover_images'),
        ),
    ]
