# Generated by Django 4.0.2 on 2022-05-01 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
        ('Article', '0003_article_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='helper.prolang'),
        ),
    ]
